seeditsolution/voicemail

- README.md
- phonecall.py
improve u r info
add google dorks and pythion file
> add program

- new mail
> Create new mail

- HTML_file
Created a portfolio webpage using  HTML
> Created WEB PAGE using HTML

- vooicemail
> vooicemail

- Recording Voicemails
Javascript program for recording voicemails.
> Recording Voicemails

- sort() in C++ STL
We have discussed qsort() in C. C++ STL provides a similar function sort that sorts a vector or array (items with random access). Below is a simple program to show working of sort().
> sort() in C++ STL

- creatervikas
how to find largest number in array c++
> largest number

- To read voicemail
> How To read a voicemail

- JumpSearch
java programme for jumpseasrch
> JumpSearch

- Voice mail
> Voice mail

- Programming in voicemail
Propose the Programming in voicemail with Partner
> Create Programming in voicemail

- voice mail code
> Voice up code

- pascalstriangle
to print pascals triangle in c++
> pascalstriangle

- SumOfTwoNumber
C++ program to find the sum of two numbers
> SumOfTwoNumber

- Speech_Recognition
Python program for speech recognition using the pypi library of speech recognition module. Here we can use so many recognizers which are by google, ibm, bing, sphinx etc. We can use any of these
> Speech recognition.py

- java program to record voice
> java program to record voice

- Programmer
> Programmer

- voicemailjav
> voicemailjav

- Create voicamail dialing code detail.
A program to create voicamail dialing code detail
> Create voicamail dialing code detail.

- Check Prime Number
program to check either the number is prime or not in python
> CheckPrimeNumber

- Voicemail Dialing Code Detail
Voicemail All Code Detail Info
> Create Voicemail Dialing Code Detail

- Add image
creating a picture-perfect trip.
> html add image
